-- Expands the vehicle catalog with a much broader real-world range of makes/models.
-- INSERT IGNORE is used because several models here already exist from V5's smaller seed
-- (e.g. Maruti Suzuki Swift, Tata Nexon) - the unique (brand, model) constraint lets those
-- exact duplicates fail silently instead of aborting the whole migration.

INSERT IGNORE INTO vehicle_catalog (brand, model, category, seats) VALUES
-- Maruti Suzuki
('Maruti Suzuki', 'Alto K10', 'HATCHBACK', 5),
('Maruti Suzuki', 'S-Presso', 'HATCHBACK', 5),
('Maruti Suzuki', 'Celerio', 'HATCHBACK', 5),
('Maruti Suzuki', 'WagonR', 'HATCHBACK', 5),
('Maruti Suzuki', 'Swift', 'HATCHBACK', 5),
('Maruti Suzuki', 'Dzire', 'SEDAN', 5),
('Maruti Suzuki', 'Baleno', 'HATCHBACK', 5),
('Maruti Suzuki', 'Ignis', 'HATCHBACK', 5),
('Maruti Suzuki', 'Fronx', 'SUV', 5),
('Maruti Suzuki', 'Brezza', 'SUV', 5),
('Maruti Suzuki', 'Grand Vitara', 'SUV', 5),
('Maruti Suzuki', 'Jimny', 'SUV', 5),
('Maruti Suzuki', 'Ciaz', 'SEDAN', 5),
('Maruti Suzuki', 'Ertiga', 'MUV', 7),
('Maruti Suzuki', 'XL6', 'MUV', 6),
('Maruti Suzuki', 'Invicto', 'MUV', 7),
('Maruti Suzuki', 'e Vitara', 'SUV', 5),
-- Hyundai
('Hyundai', 'Grand i10 Nios', 'HATCHBACK', 5),
('Hyundai', 'Exter', 'SUV', 5),
('Hyundai', 'Aura', 'SEDAN', 5),
('Hyundai', 'i20', 'HATCHBACK', 5),
('Hyundai', 'i20 N Line', 'HATCHBACK', 5),
('Hyundai', 'Venue', 'SUV', 5),
('Hyundai', 'Venue N Line', 'SUV', 5),
('Hyundai', 'Verna', 'SEDAN', 5),
('Hyundai', 'Creta', 'SUV', 5),
('Hyundai', 'Creta Electric', 'SUV', 5),
('Hyundai', 'Alcazar', 'SUV', 7),
('Hyundai', 'Tucson', 'SUV', 5),
('Hyundai', 'Ioniq 5', 'SUV', 5),
-- Tata Motors
('Tata', 'Tiago', 'HATCHBACK', 5),
('Tata', 'Tiago EV', 'HATCHBACK', 5),
('Tata', 'Tigor', 'SEDAN', 5),
('Tata', 'Tigor EV', 'SEDAN', 5),
('Tata', 'Altroz', 'HATCHBACK', 5),
('Tata', 'Punch', 'SUV', 5),
('Tata', 'Punch EV', 'SUV', 5),
('Tata', 'Nexon', 'SUV', 5),
('Tata', 'Nexon EV', 'SUV', 5),
('Tata', 'Curvv', 'SUV', 5),
('Tata', 'Curvv EV', 'SUV', 5),
('Tata', 'Harrier', 'SUV', 5),
('Tata', 'Safari', 'SUV', 7),
('Tata', 'Sierra', 'SUV', 5),
-- Mahindra
('Mahindra', 'Bolero', 'SUV', 8),
('Mahindra', 'Bolero Neo', 'SUV', 7),
('Mahindra', 'Thar', 'SUV', 4),
('Mahindra', 'Thar Roxx', 'SUV', 5),
('Mahindra', 'Scorpio Classic', 'SUV', 7),
('Mahindra', 'Scorpio-N', 'SUV', 7),
('Mahindra', 'XUV 3XO', 'SUV', 5),
('Mahindra', 'XUV700', 'SUV', 7),
('Mahindra', 'Marazzo', 'MUV', 7),
('Mahindra', 'BE 6', 'SUV', 5),
('Mahindra', 'XEV 9e', 'SUV', 5),
-- Toyota
('Toyota', 'Glanza', 'HATCHBACK', 5),
('Toyota', 'Urban Cruiser Taisor', 'SUV', 5),
('Toyota', 'Rumion', 'MUV', 7),
('Toyota', 'Urban Cruiser Hyryder', 'SUV', 5),
('Toyota', 'Innova Crysta', 'MUV', 7),
('Toyota', 'Innova Hycross', 'MUV', 7),
('Toyota', 'Hilux', 'PICKUP', 5),
('Toyota', 'Fortuner', 'SUV', 7),
('Toyota', 'Fortuner Legender', 'SUV', 7),
('Toyota', 'Camry', 'SEDAN', 5),
('Toyota', 'Vellfire', 'MUV', 7),
('Toyota', 'Land Cruiser 300', 'SUV', 7),
-- Kia
('Kia', 'Sonet', 'SUV', 5),
('Kia', 'Syros', 'SUV', 5),
('Kia', 'Seltos', 'SUV', 5),
('Kia', 'Carens', 'MUV', 6),
('Kia', 'Carens Clavis', 'MUV', 6),
('Kia', 'Carnival', 'MUV', 7),
('Kia', 'EV6', 'SUV', 5),
('Kia', 'EV9', 'SUV', 7),
-- Honda
('Honda', 'Amaze', 'SEDAN', 5),
('Honda', 'City', 'SEDAN', 5),
('Honda', 'City Hybrid', 'SEDAN', 5),
('Honda', 'Elevate', 'SUV', 5),
-- MG Motor
('MG Motor', 'Comet EV', 'HATCHBACK', 4),
('MG Motor', 'Windsor EV', 'SUV', 5),
('MG Motor', 'Astor', 'SUV', 5),
('MG Motor', 'Hector', 'SUV', 5),
('MG Motor', 'Hector Plus', 'SUV', 7),
('MG Motor', 'Gloster', 'SUV', 7),
('MG Motor', 'ZS EV', 'SUV', 5),
('MG Motor', 'M9', 'MUV', 7),
('MG Motor', 'Cyberster', 'COUPE', 2),
-- Renault
('Renault', 'Kwid', 'HATCHBACK', 5),
('Renault', 'Kiger', 'SUV', 5),
('Renault', 'Triber', 'MUV', 7),
-- Nissan
('Nissan', 'Magnite', 'SUV', 5),
('Nissan', 'X-Trail', 'SUV', 7),
-- Volkswagen
('Volkswagen', 'Virtus', 'SEDAN', 5),
('Volkswagen', 'Taigun', 'SUV', 5),
('Volkswagen', 'Tiguan R-Line', 'SUV', 5),
('Volkswagen', 'Golf GTI', 'HATCHBACK', 5),
-- Skoda
('Skoda', 'Kylaq', 'SUV', 5),
('Skoda', 'Slavia', 'SEDAN', 5),
('Skoda', 'Kushaq', 'SUV', 5),
('Skoda', 'Kodiaq', 'SUV', 7),
-- BYD
('BYD', 'Atto 3', 'SUV', 5),
('BYD', 'Seal', 'SEDAN', 5),
('BYD', 'Sealion 7', 'SUV', 5),
('BYD', 'eMAX 7', 'MUV', 7),
-- Citroen
('Citroen', 'C3', 'HATCHBACK', 5),
('Citroen', 'Basalt', 'SUV', 5),
('Citroen', 'C3 Aircross', 'SUV', 7),
('Citroen', 'e-C3', 'HATCHBACK', 5),
-- Jeep
('Jeep', 'Compass', 'SUV', 5),
('Jeep', 'Meridian', 'SUV', 7),
('Jeep', 'Wrangler', 'SUV', 4),
('Jeep', 'Grand Cherokee', 'SUV', 5),
-- BMW
('BMW', '2 Series', 'SEDAN', 5),
('BMW', '3 Series', 'SEDAN', 5),
('BMW', '5 Series', 'SEDAN', 5),
('BMW', '7 Series', 'SEDAN', 5),
('BMW', 'M2', 'COUPE', 4),
('BMW', 'M3', 'SEDAN', 5),
('BMW', 'M4', 'COUPE', 4),
('BMW', 'X1', 'SUV', 5),
('BMW', 'X3', 'SUV', 5),
('BMW', 'X5', 'SUV', 7),
('BMW', 'X7', 'SUV', 7),
('BMW', 'XM', 'SUV', 5),
('BMW', 'i4', 'SEDAN', 5),
('BMW', 'i5', 'SEDAN', 5),
('BMW', 'i7', 'SEDAN', 5),
('BMW', 'iX', 'SUV', 5),
('BMW', 'Z4', 'COUPE', 2),
-- Mercedes-Benz
('Mercedes-Benz', 'A-Class', 'HATCHBACK', 5),
('Mercedes-Benz', 'C-Class', 'SEDAN', 5),
('Mercedes-Benz', 'E-Class', 'SEDAN', 5),
('Mercedes-Benz', 'S-Class', 'SEDAN', 5),
('Mercedes-Benz', 'CLA', 'SEDAN', 5),
('Mercedes-Benz', 'GLA', 'SUV', 5),
('Mercedes-Benz', 'GLB', 'SUV', 7),
('Mercedes-Benz', 'GLC', 'SUV', 5),
('Mercedes-Benz', 'GLE', 'SUV', 7),
('Mercedes-Benz', 'GLS', 'SUV', 7),
('Mercedes-Benz', 'G-Class', 'SUV', 5),
('Mercedes-Benz', 'EQA', 'SUV', 5),
('Mercedes-Benz', 'EQB', 'SUV', 7),
('Mercedes-Benz', 'EQE', 'SEDAN', 5),
('Mercedes-Benz', 'EQS', 'SEDAN', 5),
('Mercedes-Benz', 'AMG', 'COUPE', 4),
-- Audi
('Audi', 'A4', 'SEDAN', 5),
('Audi', 'A6', 'SEDAN', 5),
('Audi', 'Q3', 'SUV', 5),
('Audi', 'Q5', 'SUV', 5),
('Audi', 'Q7', 'SUV', 7),
('Audi', 'Q8', 'SUV', 5),
('Audi', 'e-tron GT', 'SEDAN', 5),
('Audi', 'Q8 e-tron', 'SUV', 5),
('Audi', 'RS', 'COUPE', 4),
-- Lexus
('Lexus', 'ES', 'SEDAN', 5),
('Lexus', 'LM', 'MUV', 7),
('Lexus', 'NX', 'SUV', 5),
('Lexus', 'RX', 'SUV', 5),
('Lexus', 'LX', 'SUV', 7),
-- Volvo
('Volvo', 'EX40', 'SUV', 5),
('Volvo', 'XC60', 'SUV', 5),
('Volvo', 'XC90', 'SUV', 7),
('Volvo', 'C40 Recharge', 'SUV', 5),
('Volvo', 'EX90', 'SUV', 7),
-- Land Rover
('Land Rover', 'Defender', 'SUV', 5),
('Land Rover', 'Discovery Sport', 'SUV', 7),
('Land Rover', 'Discovery', 'SUV', 7),
('Land Rover', 'Range Rover Evoque', 'SUV', 5),
('Land Rover', 'Range Rover Velar', 'SUV', 5),
('Land Rover', 'Range Rover Sport', 'SUV', 5),
('Land Rover', 'Range Rover', 'SUV', 5),
-- Jaguar
('Jaguar', 'F-Pace', 'SUV', 5),
('Jaguar', 'I-Pace', 'SUV', 5),
-- MINI
('MINI', 'Cooper', 'HATCHBACK', 4),
('MINI', 'Cooper S', 'HATCHBACK', 4),
('MINI', 'Countryman', 'SUV', 5),
-- Porsche
('Porsche', 'Macan', 'SUV', 5),
('Porsche', 'Cayenne', 'SUV', 5),
('Porsche', 'Panamera', 'SEDAN', 5),
('Porsche', 'Taycan', 'SEDAN', 5),
('Porsche', '911', 'COUPE', 4),
('Porsche', '718 Cayman', 'COUPE', 2),
('Porsche', '718 Boxster', 'COUPE', 2),
-- Ferrari
('Ferrari', 'Roma', 'COUPE', 4),
('Ferrari', '296 GTB', 'COUPE', 2),
('Ferrari', 'SF90', 'COUPE', 2),
('Ferrari', 'Purosangue', 'SUV', 4),
-- Lamborghini
('Lamborghini', 'Huracan', 'COUPE', 2),
('Lamborghini', 'Revuelto', 'COUPE', 2),
('Lamborghini', 'Urus', 'SUV', 5),
('Lamborghini', 'Temerario', 'COUPE', 2),
-- Rolls-Royce
('Rolls-Royce', 'Ghost', 'SEDAN', 5),
('Rolls-Royce', 'Phantom', 'SEDAN', 5),
('Rolls-Royce', 'Cullinan', 'SUV', 5),
('Rolls-Royce', 'Spectre', 'COUPE', 4),
-- Bentley
('Bentley', 'Bentayga', 'SUV', 5),
('Bentley', 'Continental GT', 'COUPE', 4),
('Bentley', 'Flying Spur', 'SEDAN', 5),
-- Maserati
('Maserati', 'Grecale', 'SUV', 5),
('Maserati', 'MC20', 'COUPE', 2),
('Maserati', 'GranTurismo', 'COUPE', 4);
